namespace: garnser
name: privx
version: 0.1.8
authors:
  - Jonathan Petersson <jpetersson@garnser.se>
readme: README.md
tags:
  - privx
  - security
  - api
license_file: LICENSE
repository: "https://github.com/garnser/garnser.privx"
