namespace: garnser
name: privx
version: 0.1.2
authors:
  - Jonathan Petersson <jpetersson@garnser.se>
readme: README.md
tags:
  - privx
  - security
  - api
dependencies:
  ansible.builtin: "*"
license_file: LICENSE
repository: https://github.com/garnser/community.privx
